experiment:
  name: ""
  note: "Famfold training config"
  seed: 42

data:
  base_path: "data/ArchiveII.csv"
  partition_path: "data/famfold/ArchiveII_famfold.csv"
  partition_scheme: "famfold"
  fold: "" 

model:
  evaluate: true
  load_pretrained: false
  pretrained_path: "path/to/pretrained/model.ckptS"
  timesteps: 5
